export const TOGGLE_VIEWER = "TOGGLE_VIEWER";
export const LOAD_NOTE = "LOAD_NOTE";
export const LOAD_NOTES = "LOAD_NOTES";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const ADD_NOTE = "ADD_NOTE";
export const TOGGLE_AUTOSAVE = "TOGGLE_AUTOSAVE";
export const UPDATE_AUTOSAVE_INTERVAL = "UPDATE_AUTOSAVE_INTERVAL";
